version: "3"

services:
  # app(docker)サービス
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/ECsite
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=ECsite.settings.prod
      - STRIPE_PUBLISHABLE_KEY=pk_test_51HUuDmAMG1JbjSh1USGPtVxGy5EyyoNUvWFzIljZnZRSBpUiFhfxssrE5IFivvVehYmNl7t8EnxbB5hTWyvX9pYg00TS5UJqQP
      - STRIPE_SECRET_KEY=sk_test_51HUuDmAMG1JbjSh1DYWM9Fo6O2hzBfk3TplkF08IwjkcozyHhVtMuOMNOcDaFMuDfqmP0WVHqqASbss8lonx94BV006RFMHi03
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  # db(postgresサービス)
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
