# Generated by Django 2.2.9 on 2020-09-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200915_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.BooleanField(default=True),
        ),
    ]
