# Generated by Django 2.2.9 on 2020-11-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='xl', max_length=10),
            preserve_default=False,
        ),
    ]
